package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setLastloginTime(java.util.Date lastloginTime) {
		set("lastloginTime", lastloginTime);
		return (M)this;
	}
	
	public java.util.Date getLastloginTime() {
		return get("lastloginTime");
	}

	public M setIsAdmin(java.lang.String isAdmin) {
		set("isAdmin", isAdmin);
		return (M)this;
	}
	
	public java.lang.String getIsAdmin() {
		return getStr("isAdmin");
	}

}
